apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-demo
  labels:
    app: bluegreen-demo
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bluegreen-demo
  template:
    metadata:
      labels:
        app: bluegreen-demo
    spec:
      containers:
      - name: bluegreen-demo
        image: argoproj/rollouts-demo:slow-purple
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  strategy:
    blueGreen:
    #https://argo-rollouts.readthedocs.io/en/stable/features/bluegreen/#configurable-features
      autoPromotionEnabled: false
      autoPromotionSeconds: 45
      previewReplicaCount: 2
      scaleDownDelaySeconds: 15
      activeService: bluegreen-demo
      previewService: bluegreen-demo-preview
